/* SHEET 18 — "Clock Island": a Gothic tower on a hill, crowned by a heap of machinery.
   True 3D masses for perspective and occlusion; every face then gets dense hand-inked detail projected onto it. */
(window.SCENES = window.SCENES || []).push({
  name: 'Clock Island', seed: 4242, ink: '#0c0c0c', theme: 'pencil',
  build(P, n, t) {
    const S = Sketch, D = S.D3, V = S.V3, TAU = S.TAU, lerp = S.lerp, K = '#0c0c0c', Wh = '#ffffff', R = (a, b) => P.r(a, b);
    const CAM = D.camera({ eye: [-1100, -1700, 420], target: [0, 0, 260], f: 2000, cx: 800, cy: 380 });
    const faces = [], add = f => { (Array.isArray(f) ? f : [f]).forEach(x => faces.push(x)); return f; };
    const custom = (c, fn, bias = 4) => faces.push({ custom: fn, c, bias });
    const box = (x0, y0, z0, x1, y1, z1, o = {}) => D.extrude([[x0, y0], [x1, y0], [x1, y1], [x0, y1]], z0, z1, Object.assign({ crease: 0.3, bottom: true }, o));
    const face = (fs, nx, ny, nz) => fs.find(f => Math.abs(f.n[0] - nx) + Math.abs(f.n[1] - ny) + Math.abs(f.n[2] - nz) < 0.05);
    /* orient: map local frame (z = axis) to point A along dir */
    const orient = (fs, A, dir) => { const w = V.norm(dir), u = V.norm(V.cross(Math.abs(w[2]) < 0.9 ? [0, 0, 1] : [1, 0, 0], w)), v = V.cross(w, u); const M = p => [A[0] + u[0] * p[0] + v[0] * p[1] + w[0] * p[2], A[1] + u[1] * p[0] + v[1] * p[1] + w[1] * p[2], A[2] + u[2] * p[0] + v[2] * p[1] + w[2] * p[2]], N = p => [u[0] * p[0] + v[0] * p[1] + w[0] * p[2], u[1] * p[0] + v[1] * p[1] + w[1] * p[2], u[2] * p[0] + v[2] * p[1] + w[2] * p[2]]; return fs.map(f => Object.assign({}, f, { v: f.v.map(M), n: N(f.n), hdir: f.hdir ? N(f.hdir) : undefined })); };
    const pipe = (A, B, r, o = {}) => { const d = V.sub(B, A), L = Math.hypot(d[0], d[1], d[2]); add(orient(D.cylinder(0, 0, r, 0, L, o.seg || 16), A, d)); (o.flanges || []).forEach(t2 => add(orient(D.cylinder(0, 0, r * 1.35, t2 * L - 2, t2 * L + 2, o.seg || 16), A, d))); };
    const planeProj = (O, U, Vv) => (u, v) => { const p = CAM.project([O[0] + U[0] * u + Vv[0] * v, O[1] + U[1] * u + Vv[1] * v, O[2] + U[2] * u + Vv[2] * v]); return p ? [p[0], p[1]] : [0, 0]; };
    /* ---------- 2D ink vocabulary used on facades (all in plane coordinates u,v; pr maps to screen) ---------- */
    const black = pts => P.wash(pts, '#060606', 1, { edge: 0, jit: 0, steps: 1 });
    const white = pts => P.occlude(pts, Wh);
    const polyL = (pts, w = 1, c = K, closed = true) => P.path(closed ? pts.concat([pts[0]]) : pts, { w, c, a: 0.95, rough: 0.25, passes: 1 });
    const archUV = (u0, u1, v0, v1, pointed = true, k = 10) => { const w = u1 - u0, rise = pointed ? w * 0.75 : w / 2, sp = v1 - rise, pts = [[u0, v0], [u0, sp]]; if (pointed) { const Rr = (w * w / 4 + rise * rise) / w; for (let i = 1; i <= k; i++) { const th = Math.PI - (Math.PI - Math.atan2(rise, w / 2 - Rr)) * i / k; pts.push([u0 + Rr + Rr * Math.cos(th), sp + Rr * Math.sin(th)]); } for (let i = k - 1; i >= 1; i--) { const th = Math.PI - (Math.PI - Math.atan2(rise, w / 2 - Rr)) * i / k; pts.push([u1 - Rr - Rr * Math.cos(th), sp + Rr * Math.sin(th)]); } } else for (let i = 1; i < 2 * k; i++) { const th = Math.PI - Math.PI * i / (2 * k); pts.push([u0 + w / 2 + Math.cos(th) * w / 2, sp + Math.sin(th) * w / 2]); } pts.push([u1, sp], [u1, v0]); return pts; };
    const lancet = (pr, u0, u1, v0, v1, o = {}) => { const A = archUV(u0, u1, v0, v1, o.round !== true), S2 = A.map(([u, v]) => pr(u, v)); const fr = archUV(u0 - 3, u1 + 3, v0 - 2, v1 + 3, o.round !== true).map(([u, v]) => pr(u, v)); polyL(fr, 0.8); black(S2); polyL(S2, 1.2);
      const um = (u0 + u1) / 2; if (u1 - u0 > 10) { const a = pr(um, v0), b = pr(um, v1 - (u1 - u0) * 0.55); P.line(a[0], a[1], b[0], b[1], { w: 1, c: Wh, passes: 1, over: 0, rough: 0.1 }); const c = pr(um, v1 - (u1 - u0) * 0.35), rr = Math.hypot(pr(u0, v0)[0] - pr(u1, v0)[0], 0) * 0.16; P.circle(c[0], c[1], rr, { w: 0.8, c: Wh, passes: 1 }); for (let v = v0 + 12; v < v1 - (u1 - u0); v += 12) { const l1 = pr(u0 + 1, v), l2 = pr(u1 - 1, v); P.line(l1[0], l1[1], l2[0], l2[1], { w: 0.5, c: Wh, a: 0.7, passes: 1, over: 0 }); } } };
    const dotsAlong = (pr, u0, v0, u1, v1, step = 5, r = 0.9) => { const L = Math.hypot(u1 - u0, v1 - v0), D2 = []; for (let s = 0; s <= L; s += step) { const q = pr(lerp(u0, u1, s / L), lerp(v0, v1, s / L)); D2.push([q[0], q[1], r]); } P.dots(D2, K, 0.9); };
    const lineUV = (pr, u0, v0, u1, v1, w = 0.9, c = K) => { const a = pr(u0, v0), b = pr(u1, v1); P.line(a[0], a[1], b[0], b[1], { w, c, passes: 1, over: 0, rough: 0.25 }); };
    const puffs2D = (poly, n, rMax) => { for (let i = 0; i < n; i++) { let x0 = 1e9, y0 = 1e9, x1 = -1e9, y1 = -1e9; poly.forEach(([x, y]) => { x0 = Math.min(x0, x); x1 = Math.max(x1, x); y0 = Math.min(y0, y); y1 = Math.max(y1, y); }); const x = R(x0, x1), y = R(y0, y1), r = R(3, rMax); if (!S.pip(poly, x, y) || !S.pip(poly, x + r, y) || !S.pip(poly, x - r, y) || !S.pip(poly, x, y + r) || !S.pip(poly, x, y - r)) continue; const b = P.sample(Array.from({ length: 9 }, (_, k) => { const a = k * TAU / 9; return [x + Math.cos(a) * r * R(0.8, 1.15), y + Math.sin(a) * r * R(0.8, 1.15)]; }), true, 2); white(b); for (let q = 0; q < b.length; q += 2) { const [bx, by] = b[q], a = Math.atan2(by - y, bx - x); if (Math.cos(a + 2.3) > -0.2) continue; P.line(bx, by, bx - Math.cos(a) * r * 0.3, by - Math.sin(a) * r * 0.3, { w: 0.5, c: K, passes: 1, over: 0, rough: 0.1 }); } polyL(b, 1); } };


    /* ---------- Peter-style 2D marks, studied from the originals ---------- */
    // fringe shading: rows of short strokes perpendicular to the outline, massed on the shadow side
    const fringe = (pts, cx, cy, r, o = {}) => { const rows = o.rows ?? 3, dens = o.every ?? 1; for (let i = 0; i < pts.length; i += dens) { const [x, y] = pts[i], a = Math.atan2(y - cy, x - cx), sh = -Math.cos(a - (o.light ?? -2.4)); if (sh < -0.05) continue; for (let m = 0; m < rows; m++) { const s0 = 1 + m * r * 0.09, L = r * (0.1 + 0.16 * sh) * (1 - m * 0.25); if (L < 1) continue; P.line(x - Math.cos(a) * s0, y - Math.sin(a) * s0, x - Math.cos(a) * (s0 + L), y - Math.sin(a) * (s0 + L), { w: 0.45, c: K, passes: 1, over: 0, rough: 0.1 }); } } };
    const lump = (cx, cy, r, o = {}) => { const k = 12, pts = P.sample(Array.from({ length: k }, (_, i) => { const a = i * TAU / k; return [cx + Math.cos(a) * r * R(0.8, 1.15), cy + Math.sin(a) * r * (o.sq ?? 0.85) * R(0.8, 1.12)]; }), true, 2); white(pts); fringe(pts, cx, cy, r, o); P.stipple(pts, Math.round(r * r * 0.18), { a: 0.9, r: 0.6, c: K, fade: (x, y) => Math.max(0, ((x - cx) * 0.7 + (y - cy)) / (r * 1.2)) }); polyL(pts, o.w ?? 1.5); if (o.double) polyL(pts.map(([x, y]) => [cx + (x - cx) * 0.86, cy + (y - cy) * 0.86]), 0.5); return pts; };
    const ballStick = (x, y, a, L, w = 0.8, c = K) => { const ex = x + Math.cos(a) * L, ey = y + Math.sin(a) * L; P.line(x, y, ex, ey, { w, c, passes: 1, over: 0, rough: 0.15 }); P.dot(ex, ey, w * 1.8 + 0.4, { c }); };
    const cloudCluster = (x, y, z, n, rMax, bias) => custom([x, y, z], (PP, cm) => { const c = cm.project([x, y, z]); if (!c) return; for (let q = 0; q < n; q++) lump(c[0] + R(-rMax * 1.6, rMax * 1.6), c[1] + R(-rMax * 1.1, rMax * 1.1) - q * 1.4, R(rMax * 0.45, rMax), { rows: 3 }); }, bias);
    const banded = (A, B, r, bands, o = {}) => { pipe(A, B, r, { seg: 18, flanges: bands }); custom([(A[0] + B[0]) / 2, (A[1] + B[1]) / 2, (A[2] + B[2]) / 2], (PP, cm) => { bands.forEach(t2 => { const p = [lerp(A[0], B[0], t2), lerp(A[1], B[1], t2), lerp(A[2], B[2], t2)], d = V.norm(V.sub(B, A)), u = V.norm(V.cross(d, [0, 0, 1])), w = V.cross(u, d); for (let k = 0; k < 10; k++) { const a = Math.PI * 0.6 + k * 0.28, q = V.add(p, V.add(V.mul(u, Math.cos(a) * r * 1.36), V.mul(w, Math.sin(a) * r * 1.36))), s = cm.project(q); if (s) PP.dot(s[0], s[1], 1, { c: K }); } }); }, 6); };

    /* ================= THE ISLAND: a thick rock slab ================= */
    const isl = []; for (let k = 0; k < 22; k++) { const a = k * TAU / 22; isl.push([Math.cos(a) * R(360, 440) + 20, Math.sin(a) * R(250, 310)]); }
    const ISL = D.extrude(isl, -70, 0, { crease: 0.4 }); add(ISL);
    ISL.filter(f => Math.abs(f.n[2]) < 0.5).forEach(f => { f.deco = (PP, cm, poly) => { for (let i = 0; i < 6; i++) { const a = poly[0], b = poly[1], c = poly[2], d = poly[3], t2 = R(0.1, 0.9), p1 = [lerp(a[0], b[0], t2), lerp(a[1], b[1], t2)], p2 = [lerp(d[0], c[0], t2 + R(-0.1, 0.1)), lerp(d[1], c[1], t2)]; PP.curve([p1, [lerp(p1[0], p2[0], 0.5) + R(-4, 4), lerp(p1[1], p2[1], 0.5)], p2], { w: 0.6, c: K, rough: 0.5, passes: 1 }); } }; });
    face(ISL, 0, 0, 1).deco = (PP) => { for (let i = 0; i < 160; i++) { const a = R(0, TAU), d = Math.sqrt(R(0, 1)), x = Math.cos(a) * d * 380 + 20, y = Math.sin(a) * d * 260, q = CAM.project([x, y, 0]); if (!q || Math.hypot(x, y) < 120) continue; if (P.R() > 0.5) PP.curve([[q[0], q[1]], [q[0] + R(-1.5, 1.5), q[1] - R(3, 8)]], { w: 0.6, c: K, rough: 0.2, passes: 1 }); else { PP.ellipse(q[0], q[1], R(2, 5), R(1, 2.4), { w: 0.7, c: K, passes: 1 }); } } };

    /* ================= THE CLOCK-LIGHTHOUSE: an octagonal tower ================= */
    const OCT = (r, z0, z1) => D.extrude(Array.from({ length: 8 }, (_, k) => [Math.cos(k * TAU / 8 + TAU / 16) * r, Math.sin(k * TAU / 8 + TAU / 16) * r]), z0, z1, { crease: 0.3 });
    const T1 = OCT(96, 0, 240), T2 = OCT(80, 240, 420), T3 = OCT(66, 420, 470); add(T1); add(T2); add(T3);
    add(OCT(104, 234, 246)); add(OCT(88, 414, 426));
    const octFace = (fs, zlo, zhi, r, fn) => fs.filter(f => Math.abs(f.n[2]) < 0.5).forEach(f => { const v = f.v, O = [v[0][0], v[0][1], zlo], Ux = V.sub([v[1][0], v[1][1], zlo], O), wid = Math.hypot(Ux[0], Ux[1]), U = V.mul(Ux, 1 / wid); f.deco = () => fn(planeProj(O, U, [0, 0, 1]), wid, zhi - zlo, f.n); });
    octFace(T1, 0, 240, 96, (pr, wid, h, nrm) => { const front = nrm[1] < -0.8; if (front) { const A = archUV(wid * 0.18, wid * 0.82, 0, 150).map(([u, v]) => pr(u, v)); black(A); for (let i = 0; i < 700; i++) { const q = pr(R(wid * 0.22, wid * 0.78), R(6, 140)); if (!S.pip(A, q[0], q[1])) continue; } for (let k = 0; k < 16; k++) { const q = pr(R(wid * 0.24, wid * 0.76), R(10, 130)); const rr = R(4, 10), bl = P.sample(Array.from({ length: 9 }, (_, i) => [q[0] + Math.cos(i * TAU / 9) * rr * R(0.8, 1.2), q[1] + Math.sin(i * TAU / 9) * rr * R(0.8, 1.2)]), true, 1.5); if (!bl.every(([x, y]) => S.pip(A, x, y))) continue; white(bl); polyL(bl, 0.9); P.dot(q[0] + rr * 0.2, q[1], 1, { c: K }); fringe(bl, q[0], q[1], rr, { rows: 2 }); } polyL(A, 1.4); [0, 4, 8].forEach(d => polyL(archUV(wid * 0.18 - d, wid * 0.82 + d, 0, 150 + d * 1.4).map(([u, v]) => pr(u, v)), d ? 0.7 : 1.3)); }
      else { lancet(pr, wid * 0.2, wid * 0.44, 30, 150); lancet(pr, wid * 0.56, wid * 0.8, 30, 150); }
      lancet(pr, wid * 0.25, wid * 0.75, 170, 228); dotsAlong(pr, 2, 160, wid - 2, 160, 5, 1); dotsAlong(pr, 2, 16, wid - 2, 16, 6, 0.9); for (let v = 20; v < 230; v += 8) if (P.R() > 0.6) { const u0 = R(2, wid - 12); lineUV(pr, u0, v, u0 + R(4, 10), v, 0.45); } });
    octFace(T2, 240, 420, 80, (pr, wid, h, nrm) => { const front = nrm[1] < -0.8 || (nrm[0] < -0.2 && nrm[1] < -0.2); for (let k = 0; k < 3; k++) lancet(pr, wid * (0.1 + k * 0.3), wid * (0.3 + k * 0.3), 250 - 240, 330 - 240, { round: k === 1 }); dotsAlong(pr, 2, 100, wid - 2, 100, 5, 1); for (let v = 110; v < 175; v += 7) lineUV(pr, 1, v, wid - 1, v, 0.35); void front; });
    /* the great clock on the front upper face */
    { const f = T2.find(f => f.n[1] < -0.9), v = f.v, cx = (v[0][0] + v[1][0]) / 2, cy = v[0][1] - 2, cz = 360;
      add(orient(D.cylinder(0, 0, 44, 0, 8, 36), [cx, cy, cz], [0, -1, 0]));
      custom([cx, cy - 12, cz], (PP, cm) => { const P0 = (a, r) => cm.project([cx + Math.cos(a) * r, cy - 8.2, cz + Math.sin(a) * r]); const ring = r => Array.from({ length: 40 }, (_, i) => P0(i * TAU / 40, r)).map(q => [q[0], q[1]]); white(ring(42)); polyL(ring(42), 1.6); polyL(ring(36), 0.8); for (let i = 0; i < 60; i++) { const a = i * TAU / 60, p1 = P0(a, 36), p2 = P0(a, i % 5 ? 39 : 41.5); PP.line(p1[0], p1[1], p2[0], p2[1], { w: i % 5 ? 0.5 : 1.3, c: K, passes: 1, over: 0 }); } ['XII', 'III', 'VI', 'IX'].forEach((s2, i) => { const q = P0(Math.PI / 2 - i * Math.PI / 2, 29); PP.text(s2, q[0], q[1] + 3, { size: 7, align: 'center', c: K }); }); for (let i = 0; i < 12; i++) { const q = P0(i * TAU / 12, 20); PP.dot(q[0], q[1], 1.2, { c: K }); } const c = P0(0, 0), h = P0(Math.PI / 2 + 0.9, 20), m = P0(Math.PI / 2 - 2.2, 32); PP.line(c[0], c[1], h[0], h[1], { w: 2.6, c: K, passes: 1, over: 0 }); PP.line(c[0], c[1], m[0], m[1], { w: 1.4, c: K, passes: 1, over: 0 }); PP.dot(c[0], c[1], 3, { c: K }); PP.stipple(ring(40), 400, { a: 0.8, r: 0.6, c: K, fade: (x, y) => Math.max(0, (x - c[0]) / 50) }); }, 30); }
    /* spiral pipe winding round the tower, banded + riveted */
    { const pts = []; for (let k = 0; k <= 60; k++) { const t2 = k / 60, a = -1.2 + t2 * TAU * 1.6, r = t2 < 0.62 ? 118 : 100, z = 20 + t2 * 390; pts.push([Math.cos(a) * r, Math.sin(a) * r, z]); } for (let k = 0; k + 1 < pts.length; k++) { pipe(pts[k], pts[k + 1], 9, { seg: 12 }); if (k % 6 === 3) add(orient(D.cylinder(0, 0, 12.4, -2, 2, 12), pts[k], V.sub(pts[k + 1], pts[k]))); } }
    /* lantern: gallery ring with railing, glazed cage with mullions, cupola, lens, big telescope */
    { const LZ = 470; add(D.cylinder(0, 0, 92, LZ, LZ + 8, 32)); add(D.ringSolid(0, 0, 50, 54, LZ + 8, LZ + 90, 24, { a0: 0, a1: TAU }));
      custom([0, -60, LZ + 50], (PP, cm) => { for (let k = 0; k < 16; k++) { const a = k * TAU / 16, p1 = cm.project([Math.cos(a) * 54, Math.sin(a) * 54, LZ + 8]), p2 = cm.project([Math.cos(a) * 54, Math.sin(a) * 54, LZ + 90]); if (!(p1 && p2)) continue; if (Math.cos(a) * (CAM.eye[0]) + Math.sin(a) * CAM.eye[1] < 0) continue; PP.line(p1[0], p1[1], p2[0], p2[1], { w: 1.2, c: K, passes: 1, over: 0 }); } [LZ + 36, LZ + 64].forEach(z => { const pts = []; for (let k = 0; k <= 32; k++) { const a = k * TAU / 32; pts.push([Math.cos(a) * 54.2, Math.sin(a) * 54.2, z]); } D.polyline3(PP, pts.filter(p => p[0] * CAM.eye[0] + p[1] * CAM.eye[1] > 0), cm, { w: 0.7, c: K }); }); for (let k = 0; k < 40; k++) { const a = k * TAU / 40, p1 = cm.project([Math.cos(a) * 90, Math.sin(a) * 90, LZ + 8]), p2 = cm.project([Math.cos(a) * 90, Math.sin(a) * 90, LZ + 26]); if (p1 && p2 && Math.cos(a) * CAM.eye[0] + Math.sin(a) * CAM.eye[1] > 0) PP.line(p1[0], p1[1], p2[0], p2[1], { w: 0.8, c: K, passes: 1, over: 0 }); } }, 40);
      add(D.revolve(0, 0, Array.from({ length: 10 }, (_, k) => { const a = Math.PI / 2 * k / 9; return [Math.cos(a) * 60 + 0.01, LZ + 90 + Math.sin(a) * 50]; }), { seg: 28 })); add(D.revolve(0, 0, [[8, LZ + 138], [2, LZ + 170], [0.01, LZ + 176]], { seg: 10 }));
      add(D.revolve(0, 0, Array.from({ length: 9 }, (_, k) => { const a = -Math.PI / 2 + Math.PI * k / 8; return [Math.cos(a) * 30 + 0.01, LZ + 50 + Math.sin(a) * 30]; }), { seg: 20 }));
      banded([30, -20, LZ + 60], [240, -180, LZ + 140], 14, [0.1, 0.3, 0.55, 0.8]); add(orient(D.cylinder(0, 0, 22, 0, 10, 24), [240, -180, LZ + 140], [210, -160, 80]));
      custom([0, 0, LZ + 180], (PP, cm) => { const b = cm.project([0, 0, LZ + 176]); if (!b) return; for (let k = 0; k < 7; k++) { const a = -Math.PI / 2 - 0.55 + k * 0.18; PP.line(b[0] + Math.cos(a) * 20, b[1] + Math.sin(a) * 20, b[0] + Math.cos(a) * R(60, 110), b[1] + Math.sin(a) * R(60, 110), { w: 0.6, c: K, passes: 1, over: 0, rough: 0.2 }); } }, 300);
    }
    /* ================= the village on the island: houses, a windmill, a stair tower ================= */
    { const house = (x, y, w, d, h, rot) => { const c = Math.cos(rot), s = Math.sin(rot), T = ([u, v]) => [x + u * c - v * s, y + u * s + v * c]; const base = [[-w, -d], [w, -d], [w, d], [-w, d]].map(T); const H = D.extrude(base, 0, h, { crease: 0.3 }); add(H); const r0 = T([-w, 0]), r1 = T([w, 0]); add(D.poly3([[...T([-w, -d]), h], [...T([w, -d]), h], [...r1, h + w * 0.9], [...r0, h + w * 0.9]], [x, y, -500], { hdir: [0, 0, 1] })); add(D.poly3([[...T([-w, d]), h], [...T([w, d]), h], [...r1, h + w * 0.9], [...r0, h + w * 0.9]], [x, y, -500], {})); add(D.poly3([[...T([-w, -d]), h], [...T([-w, d]), h], [...r0, h + w * 0.9]], [x + 1000, y, h], {})); add(D.poly3([[...T([w, -d]), h], [...T([w, d]), h], [...r1, h + w * 0.9]], [x - 1000, y, h], {}));
        H.filter(f => Math.abs(f.n[2]) < 0.5).forEach(f => { const v2 = f.v, O = [v2[0][0], v2[0][1], 0], Ux = V.sub([v2[1][0], v2[1][1], 0], O), wid = Math.hypot(Ux[0], Ux[1]); f.deco = () => { const pr = planeProj(O, V.mul(Ux, 1 / wid), [0, 0, 1]); const n2 = Math.max(1, Math.floor(wid / 22)); for (let k = 0; k < n2; k++) lancet(pr, wid * (k + 0.3) / n2, wid * (k + 0.7) / n2, h * 0.3, h * 0.8, { round: true }); for (let v3 = 6; v3 < h; v3 += 7) if (P.R() > 0.5) { const u0 = R(1, wid - 8); lineUV(pr, u0, v3, u0 + R(3, 8), v3, 0.4); } }; }); };
      house(-260, -120, 34, 26, 60, 0.2); house(-320, 40, 26, 22, 48, -0.3); house(250, -130, 30, 24, 70, 0.1); house(200, 120, 24, 20, 44, 0.5); house(-200, 170, 22, 18, 40, 0.2);
      // windmill on the right
      const wx = 330, wy = -20; add(D.revolve(wx, wy, [[34, 0], [22, 150], [0.01, 150]], { seg: 20 })); add(D.revolve(wx, wy, [[26, 150], [4, 196], [0.01, 196]], { seg: 20 }));
      custom([wx, wy - 40, 160], (PP, cm) => { const hub = [wx - 10, wy - 30, 170], hp = cm.project(hub); if (!hp) return; for (let k = 0; k < 4; k++) { const a = 0.4 + k * Math.PI / 2, tip = [hub[0] + Math.cos(a) * 12, hub[1] - 4, hub[2] + Math.sin(a) * 120], side = [hub[0] + Math.cos(a) * 12 + Math.cos(a + Math.PI / 2) * 26, hub[1] - 4, hub[2] + Math.sin(a) * 120 + Math.sin(a + Math.PI / 2) * 26], base2 = [hub[0] + Math.cos(a + Math.PI / 2) * 26 * 0.2, hub[1] - 4, hub[2] + Math.sin(a) * 20 + Math.sin(a + Math.PI / 2) * 20]; const tp = cm.project(tip), sp = cm.project(side), bp = cm.project(base2); if (!(tp && sp && bp)) continue; PP.line(hp[0], hp[1], tp[0], tp[1], { w: 2, c: K, passes: 1, over: 0 }); const sail = [[hp[0] + (tp[0] - hp[0]) * 0.18, hp[1] + (tp[1] - hp[1]) * 0.18], [tp[0], tp[1]], [sp[0], sp[1]], [bp[0], bp[1]]]; white(sail); for (let m = 1; m < 8; m++) { const t2 = m / 8; PP.line(lerp(sail[0][0], sail[1][0], t2), lerp(sail[0][1], sail[1][1], t2), lerp(sail[3][0], sail[2][0], t2), lerp(sail[3][1], sail[2][1], t2), { w: 0.6, c: K, passes: 1, over: 0 }); } PP.line(sail[3][0], sail[3][1], sail[2][0], sail[2][1], { w: 0.8, c: K, passes: 1, over: 0 }); polyL(sail, 1.1); } PP.circle(hp[0], hp[1], 6, { w: 1.4, c: K, passes: 1 }); PP.dot(hp[0], hp[1], 2.4, { c: K }); }, 200);
      // a stair tower of stacked drums with a spiral stair around it, left
      const sx = -120, sy = -200; for (let k = 0; k < 5; k++) add(D.cylinder(sx, sy, 26 - k * 3, k * 36, k * 36 + 32, 20)); for (let k = 0; k < 30; k++) { const a = k * 0.5, z = k * 6, x = sx + Math.cos(a) * 34, y = sy + Math.sin(a) * 34; add(box(x - 6, y - 6, z, x + 6, y + 6, z + 2.5)); }
    }
    cloudCluster(-150, -110, 300, 9, 18, 200); cloudCluster(130, -110, 200, 7, 15, 200); cloudCluster(-380, -60, 60, 7, 16, 120); cloudCluster(120, -100, 520, 6, 14, 300);

    /* ================= render the structure ================= */
    D.render(P, faces, CAM, { ink: K, paper: Wh, light: [-0.3, -0.75, 0.55], ambient: 0.04, w: 1.4, rough: 0.3, zw: 0, hatchMin: 0.06, rich: true, darken: 1.35, gap: 3.6, stipple: true, style: 'layered' });

    /* ================= THE UNDERWORLD hanging beneath the island (2D, Peter-style) ================= */
    { // silhouette: projected island rim, dripping down into a ragged mass
      const rim = isl.map(([x, y]) => CAM.project([x, y, -70])).filter(Boolean).map(q => [q[0], q[1]]);
      let minX = 1e9, maxX = -1e9, rimY = -1e9; rim.forEach(([x, y]) => { minX = Math.min(minX, x); maxX = Math.max(maxX, x); rimY = Math.max(rimY, y); });
      const cx = (minX + maxX) / 2, hw = (maxX - minX) / 2, top = rimY - 70;
      const under = []; for (let k = 0; k <= 40; k++) { const t2 = k / 40, x = lerp(minX + 10, maxX - 10, t2), depth = 170 * Math.pow(Math.sin(Math.PI * t2), 0.8) + 40 * Math.sin(t2 * 17) + R(-10, 10); under.push([x, Math.min(975, top + 70 + depth)]); }
      const mass = [[minX + 10, top + 60]].concat(under, [[maxX - 10, top + 60]]);
      black(mass);
      // white organic veins with ball-and-stick branches
      for (let k = 0; k < 16; k++) { let x = R(minX + 30, maxX - 30), y = top + 70, a = Math.PI / 2 + R(-0.3, 0.3); const pts = []; for (let i = 0; i < 40; i++) { a += R(-0.18, 0.18); x += Math.cos(a) * 6; y += Math.sin(a) * 6; if (!S.pip(mass, x, y)) break; pts.push([x, y]); } if (pts.length < 6) continue; const L = [], Rr = []; pts.forEach((p, i) => { const q = pts[Math.min(pts.length - 1, i + 1)], o = pts[Math.max(0, i - 1)], tx = q[0] - o[0], ty = q[1] - o[1], l = Math.hypot(tx, ty) || 1, w = 9 * (1 - i / pts.length) + 2; L.push([p[0] - ty / l * w, p[1] + tx / l * w]); Rr.push([p[0] + ty / l * w, p[1] - tx / l * w]); }); const poly = L.concat(Rr.slice().reverse()); white(poly); polyL(poly, 1); P.path(pts, { w: 0.7, c: K, rough: 0.1, passes: 1 }); pts.forEach(([px, py], i) => { if (i % 2 || i > pts.length - 2) return; const q = pts[i + 1], a2 = Math.atan2(q[1] - py, q[0] - px); ballStick(px, py, a2 + 1.4, 9 * (1 - i / pts.length) + 1, 0.6); ballStick(px, py, a2 - 1.4, 9 * (1 - i / pts.length) + 1, 0.6); }); }
      // pods, lumps, rings and eyes packed into the dark
      const placed = []; for (let i = 0; i < 4000; i++) { const r = R(4, 26), x = R(minX + 20, maxX - 20), y = R(top + 80, 960); if (!S.pip(mass, x, y) || !S.pip(mass, x, y + r) || placed.some(([a, b, c]) => Math.hypot(x - a, y - b) < c + r + 3)) continue; placed.push([x, y, r]); const k = P.R();
        if (k < 0.35) lump(x, y, r, { rows: 3, double: r > 12 }); else if (k < 0.5) { white(Array.from({ length: 18 }, (_, q) => [x + Math.cos(q * TAU / 18) * r, y + Math.sin(q * TAU / 18) * r])); for (let m = 1; m <= 4; m++) P.circle(x, y, r * m / 4, { w: m === 4 ? 1.2 : 0.6, c: K, passes: 1 }); } else if (k < 0.62) { const pts = P.sample(Array.from({ length: 10 }, (_, q) => [x + Math.cos(q * TAU / 10) * r * 0.5, y + Math.sin(q * TAU / 10) * r]), true, 2); white(pts); polyL(pts, 1.1); for (let m = -3; m <= 3; m++) P.dot(x, y + m * r * 0.22, 1.1, { c: K }); } else if (k < 0.72) { white(Array.from({ length: 16 }, (_, q) => [x + Math.cos(q * TAU / 16) * r, y + Math.sin(q * TAU / 16) * r * 0.75])); P.ellipse(x, y, r, r * 0.75, { w: 1.2, c: K, passes: 1 }); P.circle(x, y, r * 0.4, { w: 0.9, c: K, passes: 1 }); P.wash(Array.from({ length: 10 }, (_, q) => [x + Math.cos(q * TAU / 10) * r * 0.18, y + Math.sin(q * TAU / 10) * r * 0.18]), '#050505', 1, { edge: 0, steps: 1, jit: 0 }); } else { P.dot(x, y, Math.min(3, r * 0.2), { c: Wh, a: 1 }); } }
      // hanging roots and droplet threads from the underside edge
      for (let k = 0; k < 40; k++) { const t2 = R(0.02, 0.98), i = Math.round(t2 * 40), [x, y] = under[i]; if (y > 950) continue; const L = R(20, 90), pts = [[x, y - 2]]; let a = Math.PI / 2 + R(-0.3, 0.3), px = x, py = y; for (let s = 0; s < L; s += 6) { a += R(-0.2, 0.2); px += Math.cos(a) * 6; py += Math.sin(a) * 6; pts.push([px, py]); } if (py > 975) continue; P.path(pts, { w: k % 3 ? 0.9 : 2.2, c: K, rough: 0.2, passes: 1 }); if (k % 3 === 0) { const d = P.sample([[px, py - 3], [px + 3.5, py + 2], [px, py + 7], [px - 3.5, py + 2]], true, 1.5); white(d); polyL(d, 1); } else P.dot(px, py, 1.6, { c: K }); }
      // fringe of lumps along the rim where rock meets the underworld
      rim.forEach(([x, y], i) => { if (i % 1) return; });
    }
    // birds, bubbles
    for (let k = 0; k < 18; k++) { const x = R(80, 1520), y = R(60, 400), s2 = R(4, 9); if (x > 520 && x < 1150) continue; P.curve([[x - s2, y], [x - s2 * 0.4, y - s2 * 0.6], [x, y]], { w: 1, c: K, passes: 1, rough: 0.1 }); P.curve([[x, y], [x + s2 * 0.4, y - s2 * 0.6], [x + s2, y]], { w: 1, c: K, passes: 1, rough: 0.1 }); }
    P.text('CLOCK ISLAND', 1540, 966, { size: 10, align: 'right', a: 0.7 });
  }
});
